version: '3.8'

services:
  quant_trading:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      trading-net:
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: quant_trading

  market_client:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      trading-net:
    environment:
      - SERVER_HOST=quant_trading
      - SERVER_PORT=8080
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: market_client

networks:
  trading-net:
    name: trading-net

